apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-argocd
  namespace: acd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Monzy-B/argocd.git'
    path: './kubernetes-argocd'
    targetRevision: main
    helm:
      valueFiles:
        - ./kubernetes-argocd/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: alpha
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true