name: Building and testing Docker image
on:
 push:
    branches:
      # - feature/**
      # - bugfix/**
      - development
      - master
      # - tm-dev
 pull_request:
    types: [opened, synchronize, reopened, closed]
    
 workflow_dispatch:
    
jobs:   
 docker-build-and-push:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }} .
          
      - name: Push to Dockerhub
        env:
          GITHUB_SHA: ${{ github.sha }}
        if: github.ref == 'refs/heads/feature/**' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/tm-dev' && (github.event.pull_request.merged == true || github.event_name == 'push')
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}