name: Tag PR on Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.name 'Monzy_b'
          git config --global user.email 'tomiwamonehin@gmail.com'
          git config --global credential.helper store

      - name: Determine commit hash of merged PR
        id: get_commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"
      
      - name: Determine new version
        id: new_version
        run: echo "::set-output name=version::v1.0.0"  

      - name: Create and push tag
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG: ${{ steps.new_version.outputs.version }}
          COMMIT_HASH: ${{ steps.get_commit_hash.outputs.commit_hash }}
        run: |
         git fetch origin
         git checkout main
         git config --global user.name 'Monzy_b'
         git config --global user.email 'tomiwamonehin@gmail.com'
         git tag $TAG $COMMIT_HASH
         git push https://github.com/Monzy-B/argocd.git $TAG
