name: Building and testing the Docker image
on:
 push:
   branches:
    - main
 pull_request:
    types: [opened, synchronize, reopened, closed]
        
jobs:   
 docker-build-and-push:
    name: "Docker Build and Pus task"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker build .

