name: Building and testing the Docker image
on:
 push:
    branches:
      - development
      - main
    
jobs:   
 docker-build-and-push:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Git Tag
        id: generate_tag
        if: github.ref == 'refs/head/main'
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="1.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          
      - name: Push Git Tag
        if: github.ref == 'refs/head/main'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BRANCH_NAME == 'main' && 'prod-k8s' || 'dev-k8s' }}:${GITHUB_SHA::5} .
          
      - name: Push to appropriate repo
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "main" ]; then
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/prod-k8s:${GITHUB_SHA::5}
          elif [ "${{ env.BRANCH_NAME }}" == "development" ]; then
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/dev-k8s:${GITHUB_SHA::5}
          fi